### ISSUE TITLE
Peer-depend on Traceur

### ISSUE THREAD

**Issue by domenic** [aaronfrost/grunt-traceur#33]
We had a long discussion over in https://github.com/karma-runner/karma/issues/1166 about how Traceur-using build tools should depend on Traceur. Our conclusion was that the best way to deal with this was for all of them to peer-depend on Traceur, instead of depend. That way, you get a single Traceur version for the whole project, instead of grunt-traceur bundling one version, and karma-traceur-preprocessor bundling another, and so on. It also allows the user to control the version of Traceur they use, instead of having it controlled by their tools; this allows them to e.g. upgrade without having to pull-request grunt-traceur and then upgrade their grunt-traceur dependency.

Traceur is kind of a special-case, being pre-1.0 but needing collaboration between different tools. What we settled on was to peer-depend on e.g. ">= 0.0.60" if the tool depends on features only introduced in 0.0.60. (For example karma-traceur-preprocessor depends on features introduced in 0.0.51, but after we fix https://github.com/karma-runner/karma-traceur-preprocessor/issues/8 it will depend on features introduced in 0.0.60.) Normally you would want to put an upper limit, but Traceur does not have a stable API yet, so you can't do that effectively.

What do you guys think? Ready to move to a peer dependency? I'm filing similar issues on es6ify and gulp-traceur.

**Comment by aaronfrost** [comment]
@domenic sorry for taking so long on this. I am working this up tonight, and since this is my first time using peerDependencies, I am trying to see if I can get it to work like it would for a user. 

So, I removed the traceur dep from "dependencies" to "peerDepedencies", and set the value to ">=0.0.61", like you said. Now I cd to a new dir, and create a new project and run "npm install /Users/aaronfrost/blahblahblah" and it installs the latest version of traceur. However, if update the package.json in my new project and I add "traceur": "0.0.65" as the dependency, running "npm install" still installs the latest version of traceur, instead of the 0.0.65 version that I specified. How do I get the new project to install the version that I specify, rather than the latest version of traceur that is specified in the peerDependencies of grunt-traceur. 

Not sure if I was descriptive enough. Any help would be appreciated.

**Comment by aaronfrost** [comment]
I think that I got this working. Let me try it out tomorrow morning a bit more, and I will let you know.

**Comment by aaronfrost** [comment]
@mciparelli do you think that I should rev to 0.4.1 or rev to 0.5.0? This isn't an insanely large change, but it may be significant enough that we mark it with the 0.5.0 version. Thoughts?

**Comment by mciparelli** [comment]
Merged already!
